client localhost {
	ipaddr = 127.0.0.1
	secret = testing123
	require_message_authenticator = no
	nas_type = other
}

client docker_network {
	ipaddr = 172.16.0.0/12
	secret = testing123
	require_message_authenticator = no
	nas_type = other
}

client mikrotik_local {
	ipaddr = 94.231.178.181
	secret = RomVPN262006!
	shortname = mikrotik
	nas_type = mikrotik
}
